name: practice_project
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  typewritertext: ^3.0.9
  flutter_easyloading: ^3.0.5
  contained_tab_bar_view: ^0.8.0
  get: ^4.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

